### ISSUE TITLE
Minutes 2021-02-03

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#36]
### Action items

- [x] Landing page @troettge: #35.
- [x] Reviewers questionnaire @jvcasillas: draft in [gdrive](https://docs.google.com/forms/d/1qomSzakCYzEngP54xPkGdG14yEBNmC3se9rV35tjZwY/edit?usp=sharing).
- [x] Check transcription of objects and colours.
- [x] Continue RR drafting @stefanocoretta.
- [x] OSF prepping @stefanocoretta: #16.
   - Corrected TextGrids IPA transcription (@troettge would be good if you could check [here](https://github.com/jvcasillas/many_analyses/blob/master/data/dataset/objects.csv) and [here](https://github.com/jvcasillas/many_analyses/blob/master/data/dataset/colours.csv)).
   - Added extended trial lists (with additional columns).
   - Added typicality ratings from the norming study, including a summary of it. [NOTE: there were encoding issues in the original file, for *Moehre* and *Waescheklammer*, which I fixed]

### Discuss

- [x] R scripts in `scripts/r/`.
- [x] survey edits (https://github.com/jvcasillas/many_analyses/issues/1#issuecomment-771687908)

**Comment by jvcasillas** [comment]
Discussed

- [ ] Encoding issues (fixed)
- [ ] Trial list updates, includes speaker, trial number, etc. 
- [ ] Missing information about typicality in AF condition ()


For next week

- [ ] Continue working on surveys (@jvcasillas) (https://github.com/jvcasillas/many_analyses/issues/1#issuecomment-771687908)
- [ ] Include information about German phonetics/phonology, consider linking to IPA chart in German
- [ ] For logo, possibly make forking paths same width as word, consider font boldness, make plural

**Comment by troettge** [comment]
@stefano: re the transcription.

I wonder whether we should give the standard German phonemic transcription (which would be /r/ for rhotics) or the appropriate rhotic for the area which is /ʁ/  Either way I think the central vowel versions of the R are not very standard not even for the dialect. So I changed some vowels and added the standard /r/s in. Also changed the nphones accordingly. What do you think regarding the Rs stick with the uvular fricative or standard /r/?

**Comment by stefanocoretta** [comment]
> @stefano: re the transcription.
> 
> I wonder whether we should give the standard German phonemic transcription (which would be /r/ for rhotics) or the appropriate rhotic for the area which is /ʁ/ Either way I think the central vowel versions of the R are not very standard not even for the dialect. So I changed some vowels and added the standard /r/s in. Also changed the nphones accordingly. What do you think regarding the Rs stick with the uvular fricative or standard /r/?

Yup, I think the changes you made are more than reasonable. I will update the TGs accordingly!
